AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Serverless AI Maintenance Agent infrastructure

Resources:
  PropertyImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub property-images-ai-agent-${AWS::739275446782}
